name: check last version
on:
  push:
    branches: [ main ]
jobs:
  check_version:
    runs-on: ubuntu-22.04
    steps:
      - id: check_version
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: linuxserver
          repo: Heimdall
          excludes: prerelease, draft

      - name: fail when not matching
        if: steps.test.outputs.release != 'v2.5.3'
        run: echo "last version "${{ steps.test.outputs.release }}" != 'v2.5.3'" && exit 1  