name: check last version
on:
  push:
    branches: [ main ]
  # schedule:
  # -  cron: '0 10 * * *'
    
jobs:
  check_version:
    runs-on: ubuntu-22.04
    steps:
      - id: check_version
        uses: loeken/github-action-get-latest-release@master
        with:
          owner: linuxserver
          repo: Heimdall
          excludes: prerelease, draft

      - name: fail when not matching
        if: ${{secrets.release}} != 'v2.5.3'
        run: echo "last version "${{ secrets.release }}" != 'v2.5.3'" && exit 1  