name: check last version
on:
  push:
    branches: [ main ]
jobs:
  check_version:
    runs-on: ubuntu-22.04
    steps:
      - id: test
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: linuxserver
          repo: Heimdall
          excludes: prerelease, draft
    - name: fail when not matching
      if: steps.test.outputs.release != 'v2.5.2'
      run: exit 1  